# Site settings
title: ABC experiments
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Project update posts
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://torebre.github.io/abcR"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
#markdown: redcarpet
